#!/usr/bin/env bash
# Usage: ./githooks/pre-commit

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "Для изменения этой ветки нужно создать pull request"
  exit 1
fi

if ! swiftformat . --lint; then
  # Need to run swiftformat .
  echo ""
  echo "Похоже есть код, который нужно отформатировать."
  echo "Запусти в терминале команду swiftformat . в папке с проектом (точка тоже нужна)"
  exit 1
else
  # Format is OK
  exit 0
fi