# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Сгенерировать новые локализованные скриншоты"
  lane :screenshots do
    capture_screenshots(scheme: "WorkoutAppUITests")
  end

  desc "Загрузить существующие скриншоты в App Store Connect"
  lane :upload_screenshots do
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: false,
      force: true,
      submit_for_review: false,
      reject_if_possible: false,
      overwrite_screenshots: true,
      run_precheck_before_submit: false,
      skip_binary_upload: true
    )
  end

  desc "Выполнить первые 2 команды вместе"
  lane :make_and_upload_screenshots do
    screenshots
    upload_screenshots
  end

  desc "Собрать и отправить сборку в TestFlight"
  lane :release do
    build_app(
      scheme: "SwiftUI-WorkoutApp",
      export_method: "app-store",
      output_directory: "fastlane/builds",
      export_options: {
        provisioningProfiles: {
          "com.oleg991.SW-Parks" => "SwiftUI-WorkoutApp App Store (fastlane)"
        }
      }
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      apple_id: ENV["FASTLANE_APPLE_ID"]
    )
    # Удаляем файлы сборки после успешной публикации
    clean_build_artifacts
  end
end
