# A list of devices you want to take the screenshots from
devices(["iPhone 16 Pro Max", "iPhone 16 Pro", "iPhone SE (3rd generation)"])

# A list of languages which should be used. See https://docs.fastlane.tools/actions/snapshot/#available-language-codes
languages(["en-US", "ru"])

# By default, the latest version should be used automatically. If you want to change it, do it here. 
ios_version("18.1")

# Очистить папку билда перед стартом
# clean(true)

# Пропускаем открытие html-файла с результатами
skip_open_summary(true)

# Переустановить приложение перед стартом
reinstall_app(true)

# Стереть данные симулятора перед стартом
# erase_simulator(true)

# Enabling this option will configure the Simulator's system language
localize_simulator(true)

# Should snapshot stop immediately after the tests completely failed on one device?
stop_after_first_error(true)

# Количество попыток в случае ошибок
number_of_retries(0)

# Prevents packages from automatically being resolved to versions other than those recorded in the Package.resolved file
disable_package_automatic_updates(true)

# The name of the scheme which contains the UI Tests
scheme("WorkoutAppUITests")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
launch_arguments(["UITest"])

# For more information about all available options run
# fastlane action snapshot
