# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: SwiftUI-WorkoutApp CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 1

    steps:
    - uses: actions/checkout@v4

    - name: Xcode Version
      run: xcodebuild -version

    - name: Run Unit Tests
      run: |
        xcodebuild test \
        -scheme SwiftUI-WorkoutApp \
        -destination 'platform=iOS Simulator,OS=latest' \
        CODE_SIGNING_ALLOWED=NO
